[server]
port = $PORT
enableCORS = false
headless = true

[theme]
base = "light"
primaryColor = "#4B8BBE"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "sans serif"
